// <auto-generated />
using System;
using CharacterSorterSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterSorterSite.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20231005215200_AddSteinsGate")]
    partial class AddSteinsGate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterSorterSite.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/131317.jpg",
                            FranchiseId = 1,
                            Name = "Sasuke Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/284122.jpg",
                            FranchiseId = 1,
                            Name = "Itachi Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/284121.jpg",
                            FranchiseId = 1,
                            Name = "Naruto Uzumaki",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/284129.jpg",
                            FranchiseId = 1,
                            Name = "Kakashi Hatake",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/69275.jpg",
                            FranchiseId = 1,
                            Name = "Sakura Haruno",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/433353.jpg",
                            FranchiseId = 1,
                            Name = "Rock Lee",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 7,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/103576.jpg",
                            FranchiseId = 1,
                            Name = "Guy Might",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 8,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/103706.jpg",
                            FranchiseId = 1,
                            Name = "Zabuza Momochi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 9,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66177.jpg",
                            FranchiseId = 1,
                            Name = "Anko Mitarashi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 10,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/278736.jpg",
                            FranchiseId = 1,
                            Name = "Hinata Hyuuga",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 11,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/293375.jpg",
                            FranchiseId = 1,
                            Name = "Gaara ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 12,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/105538.jpg",
                            FranchiseId = 1,
                            Name = "Neji Hyuuga",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 13,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/131319.jpg",
                            FranchiseId = 1,
                            Name = "Deidara ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 14,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/131315.jpg",
                            FranchiseId = 1,
                            Name = "Shikamaru Nara",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 15,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/105421.jpg",
                            FranchiseId = 1,
                            Name = "Chouji Akimichi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 16,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/60062.jpg",
                            FranchiseId = 1,
                            Name = "Ino Yamanaka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 17,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/100216.jpg",
                            FranchiseId = 1,
                            Name = "Iruka Umino",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 18,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/103707.jpg",
                            FranchiseId = 1,
                            Name = "Haku ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 19,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/292452.jpg",
                            FranchiseId = 1,
                            Name = "Temari ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 20,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/82459.jpg",
                            FranchiseId = 1,
                            Name = "Kabuto Yakushi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 21,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/68618.jpg",
                            FranchiseId = 1,
                            Name = "Jiraiya ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 22,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/162089.jpg",
                            FranchiseId = 1,
                            Name = "Orochimaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 23,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/128074.jpg",
                            FranchiseId = 1,
                            Name = "Minato Namikaze",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 24,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/433351.jpg",
                            FranchiseId = 1,
                            Name = "Kisame Hoshigaki",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 25,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/54922.jpg",
                            FranchiseId = 1,
                            Name = "Pakkun ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 26,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/282663.jpg",
                            FranchiseId = 1,
                            Name = "Tsunade ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 27,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/295205.jpg",
                            FranchiseId = 1,
                            Name = "Tayuya ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 28,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/76260.jpg",
                            FranchiseId = 1,
                            Name = "Zetsu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 29,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/292449.jpg",
                            FranchiseId = 1,
                            Name = "Shino Aburame",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 30,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/103598.jpg",
                            FranchiseId = 1,
                            Name = "Kimimaro ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 31,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/131217.jpg",
                            FranchiseId = 1,
                            Name = "Kiba Inuzuka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 32,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/110946.jpg",
                            FranchiseId = 1,
                            Name = "Tenten ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 33,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/104664.jpg",
                            FranchiseId = 1,
                            Name = "Genma Shiranui",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 34,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/109419.jpg",
                            FranchiseId = 1,
                            Name = "Konohamaru Sarutobi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 35,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/70846.jpg",
                            FranchiseId = 1,
                            Name = "Gamabunta ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 36,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/103794.jpg",
                            FranchiseId = 1,
                            Name = "Shizune ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 37,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/68615.jpg",
                            FranchiseId = 1,
                            Name = "Kankurou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 38,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/103797.jpg",
                            FranchiseId = 1,
                            Name = "Kurenai Yuuhi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 39,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/82538.jpg",
                            FranchiseId = 1,
                            Name = "Asuma Sarutobi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 40,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/58197.jpg",
                            FranchiseId = 1,
                            Name = "Akamaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 41,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/62784.jpg",
                            FranchiseId = 1,
                            Name = "Isaribi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 42,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/5/57902.jpg",
                            FranchiseId = 1,
                            Name = "Aoi Rokushou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 43,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/57963.jpg",
                            FranchiseId = 1,
                            Name = "Matsuri ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 44,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/5/232183.jpg",
                            FranchiseId = 1,
                            Name = "Kurama ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 45,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/68520.jpg",
                            FranchiseId = 1,
                            Name = "Hiruzen Sarutobi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 46,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/103624.jpg",
                            FranchiseId = 1,
                            Name = "Katsuyu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 47,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/104665.jpg",
                            FranchiseId = 1,
                            Name = "Hayate Gekkou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 48,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/103579.jpg",
                            FranchiseId = 1,
                            Name = "Jiroubou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 49,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/4/103588.jpg",
                            FranchiseId = 1,
                            Name = "Kidoumaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 50,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/105422.jpg",
                            FranchiseId = 1,
                            Name = "Sakon ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 51,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/55519.jpg",
                            FranchiseId = 1,
                            Name = "Raiga Kurosuki",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 52,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/5/57869.jpg",
                            FranchiseId = 1,
                            Name = "Menma ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 53,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/36355.jpg",
                            FranchiseId = 1,
                            Name = "Zaku Abumi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 54,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/36354.jpg",
                            FranchiseId = 1,
                            Name = "Dosu Kinuta",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 55,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/66504.jpg",
                            FranchiseId = 1,
                            Name = "Kin Tsuchi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 56,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/104668.jpg",
                            FranchiseId = 1,
                            Name = "Yoroi Akado",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 57,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/58450.jpg",
                            FranchiseId = 1,
                            Name = "Seimei ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 58,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/103841.jpg",
                            FranchiseId = 1,
                            Name = "Shibi Aburame",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 59,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/57543.jpg",
                            FranchiseId = 1,
                            Name = "Akahoshi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 60,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/103839.jpg",
                            FranchiseId = 1,
                            Name = "Chouza Akimichi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 61,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/62769.jpg",
                            FranchiseId = 1,
                            Name = "Akio ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 62,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/104660.jpg",
                            FranchiseId = 1,
                            Name = "Ebisu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 63,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/62812.jpg",
                            FranchiseId = 1,
                            Name = "Shukaku ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 64,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/34809.jpg",
                            FranchiseId = 1,
                            Name = "Hashirama Senju",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 65,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/293367.jpg",
                            FranchiseId = 1,
                            Name = "Tobirama Senju",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 66,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/292518.jpg",
                            FranchiseId = 1,
                            Name = "Hanabi Hyuuga",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 67,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/103943.jpg",
                            FranchiseId = 1,
                            Name = "Yashamaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 68,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/110944.jpg",
                            FranchiseId = 1,
                            Name = "Moegi Kazamatsuri",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 69,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/104663.jpg",
                            FranchiseId = 1,
                            Name = "Izumo Kamizuki",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 70,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/103836.jpg",
                            FranchiseId = 1,
                            Name = "Hiashi Hyuuga",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 71,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/232233.jpg",
                            FranchiseId = 1,
                            Name = "Yugao Uzuki",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 72,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/103837.jpg",
                            FranchiseId = 1,
                            Name = "Inoichi Yamanaka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 73,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/166499.jpg",
                            FranchiseId = 1,
                            Name = "Hana Inuzuka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 74,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/103831.jpg",
                            FranchiseId = 1,
                            Name = "Tsume Inuzuka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 75,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/58401.jpg",
                            FranchiseId = 1,
                            Name = "Tsunami ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 76,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/103833.jpg",
                            FranchiseId = 1,
                            Name = "Baki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 77,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/5/62787.jpg",
                            FranchiseId = 1,
                            Name = "Yotaka ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 78,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/63709.jpg",
                            FranchiseId = 1,
                            Name = "Kamikiri Fuuma",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 79,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/57172.jpg",
                            FranchiseId = 1,
                            Name = "Sasame Fuuma",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 80,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/66168.jpg",
                            FranchiseId = 1,
                            Name = "Haruna ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 81,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/110943.jpg",
                            FranchiseId = 1,
                            Name = "Shigure ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 82,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/158745.jpg",
                            FranchiseId = 1,
                            Name = "Enma ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 83,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/62804.jpg",
                            FranchiseId = 1,
                            Name = "Mizura ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 84,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/74497.jpg",
                            FranchiseId = 1,
                            Name = "Gouzu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 85,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/74494.jpg",
                            FranchiseId = 1,
                            Name = "Meizu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 86,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/4/104662.jpg",
                            FranchiseId = 1,
                            Name = "Kotetsu Hagane",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 87,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/57642.jpg",
                            FranchiseId = 1,
                            Name = "Toki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 88,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/62776.jpg",
                            FranchiseId = 1,
                            Name = "Gamatatsu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 89,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/103948.jpg",
                            FranchiseId = 1,
                            Name = "Fugaku Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 90,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/58258.jpg",
                            FranchiseId = 1,
                            Name = "Mubi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 91,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/66171.jpg",
                            FranchiseId = 1,
                            Name = "Oki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 92,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/56420.jpg",
                            FranchiseId = 1,
                            Name = "Jirouchou Wasabi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 93,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/54034.jpg",
                            FranchiseId = 1,
                            Name = "Gamakichi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 94,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/63540.jpg",
                            FranchiseId = 1,
                            Name = "Chishima ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 95,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/53360.jpg",
                            FranchiseId = 1,
                            Name = "Tazuna ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 96,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/62778.jpg",
                            FranchiseId = 1,
                            Name = "Genno ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 97,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/66166.jpg",
                            FranchiseId = 1,
                            Name = "Todoroki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 98,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/61075.jpg",
                            FranchiseId = 1,
                            Name = "Raidou Namiashi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 99,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/57107.jpg",
                            FranchiseId = 1,
                            Name = "Karashi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 100,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/57108.jpg",
                            FranchiseId = 1,
                            Name = "Ryuugan ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 101,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/66517.jpg",
                            FranchiseId = 1,
                            Name = "Fukusuke Hikyakuya",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 102,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/130515.jpg",
                            FranchiseId = 1,
                            Name = "Ayame ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 103,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/62801.jpg",
                            FranchiseId = 1,
                            Name = "Teuchi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 104,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/66518.jpg",
                            FranchiseId = 1,
                            Name = "Jigumo Fuuma",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 105,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/57469.jpg",
                            FranchiseId = 1,
                            Name = "Arashi Fuuma",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 106,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/55003.jpg",
                            FranchiseId = 1,
                            Name = "Ranmaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 107,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/62767.jpg",
                            FranchiseId = 1,
                            Name = "Hokushin ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 108,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/58241.jpg",
                            FranchiseId = 1,
                            Name = "Renga ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 109,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/4/66172.jpg",
                            FranchiseId = 1,
                            Name = "Genzou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 110,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/63539.jpg",
                            FranchiseId = 1,
                            Name = "Gatsu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 111,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/4/86780.jpg",
                            FranchiseId = 1,
                            Name = "Dengaku ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 112,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/86790.jpg",
                            FranchiseId = 1,
                            Name = "Manabu Akado",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 113,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/63538.jpg",
                            FranchiseId = 1,
                            Name = "Hokuto ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 114,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/86791.jpg",
                            FranchiseId = 1,
                            Name = "Mondai ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 115,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/66488.jpg",
                            FranchiseId = 1,
                            Name = "Nagare ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 116,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/63537.jpg",
                            FranchiseId = 1,
                            Name = "Nanafushi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 117,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/140157.jpg",
                            FranchiseId = 1,
                            Name = "Nan ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 118,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/66158.jpg",
                            FranchiseId = 1,
                            Name = "Kazabune ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 119,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/66508.jpg",
                            FranchiseId = 1,
                            Name = "Yakumo Kurama",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 120,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/63536.jpg",
                            FranchiseId = 1,
                            Name = "Sazanami ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 121,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/57857.jpg",
                            FranchiseId = 1,
                            Name = "Senta ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 122,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/66159.jpg",
                            FranchiseId = 1,
                            Name = "Shin'emon ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 123,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/86778.jpg",
                            FranchiseId = 1,
                            Name = "Yajirobee ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 124,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66173.jpg",
                            FranchiseId = 1,
                            Name = "Tanzou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 125,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/66174.jpg",
                            FranchiseId = 1,
                            Name = "Waraji ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 126,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/158739.jpg",
                            FranchiseId = 1,
                            Name = "Aoba Yamashiro",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 127,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/63378.jpg",
                            FranchiseId = 1,
                            Name = "Jibachi Kamizuru",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 128,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/62795.jpg",
                            FranchiseId = 1,
                            Name = "Oboro ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 129,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/66175.jpg",
                            FranchiseId = 1,
                            Name = "Tsubaki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 130,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/100214.jpg",
                            FranchiseId = 1,
                            Name = "Shikaku Nara",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 131,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/57467.jpg",
                            FranchiseId = 1,
                            Name = "Mizuki Touji",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 132,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/66545.jpg",
                            FranchiseId = 1,
                            Name = "Giichi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 133,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/46484.jpg",
                            FranchiseId = 1,
                            Name = "Jantou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 134,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/86782.jpg",
                            FranchiseId = 1,
                            Name = "Kusabi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 135,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/115731.jpg",
                            FranchiseId = 1,
                            Name = "Hachidai ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 136,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/66540.jpg",
                            FranchiseId = 1,
                            Name = "Hakkaku ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 137,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/66541.jpg",
                            FranchiseId = 1,
                            Name = "Akane ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 138,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/103949.jpg",
                            FranchiseId = 1,
                            Name = "Mikoto Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 139,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66542.jpg",
                            FranchiseId = 1,
                            Name = "Inari ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 140,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/62786.jpg",
                            FranchiseId = 1,
                            Name = "Yoshino Nara",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 141,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/225775.jpg",
                            FranchiseId = 1,
                            Name = "Karura ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 142,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/103955.jpg",
                            FranchiseId = 1,
                            Name = "Homura Mitokado",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 143,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/103956.jpg",
                            FranchiseId = 1,
                            Name = "Koharu Utatane",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 144,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/103946.jpg",
                            FranchiseId = 1,
                            Name = "Dan Katou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 145,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/103835.jpg",
                            FranchiseId = 1,
                            Name = "Hizashi Hyuuga",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 146,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/103834.jpg",
                            FranchiseId = 1,
                            Name = "Kuromaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 147,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/103950.jpg",
                            FranchiseId = 1,
                            Name = "Nawaki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 148,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/86796.jpg",
                            FranchiseId = 1,
                            Name = "Tekka Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 149,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/66477.jpg",
                            FranchiseId = 1,
                            Name = "Inabi Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 150,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/63710.jpg",
                            FranchiseId = 1,
                            Name = "Yashiro Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 151,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/103604.jpg",
                            FranchiseId = 1,
                            Name = "Rasa ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 152,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/104667.jpg",
                            FranchiseId = 1,
                            Name = "Misumi Tsurugi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 153,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66533.jpg",
                            FranchiseId = 1,
                            Name = "Genyuumaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 154,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/104672.jpg",
                            FranchiseId = 1,
                            Name = "Ibiki Morino",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 155,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/62818.jpg",
                            FranchiseId = 1,
                            Name = "Zouri ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 156,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/66536.jpg",
                            FranchiseId = 1,
                            Name = "Kaiza ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 157,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66497.jpg",
                            FranchiseId = 1,
                            Name = "Ami ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 158,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/91366.jpg",
                            FranchiseId = 1,
                            Name = "Udon Ise",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 159,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/66498.jpg",
                            FranchiseId = 1,
                            Name = "Kagari ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 160,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66499.jpg",
                            FranchiseId = 1,
                            Name = "Baiu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 161,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/86793.jpg",
                            FranchiseId = 1,
                            Name = "Midare ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 162,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/86803.jpg",
                            FranchiseId = 1,
                            Name = "Tonbo Tobitake",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 163,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/66479.jpg",
                            FranchiseId = 1,
                            Name = "Teyaki Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 164,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66478.jpg",
                            FranchiseId = 1,
                            Name = "Uruchi Uchiha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 165,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/86804.jpg",
                            FranchiseId = 1,
                            Name = "Tsuba ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 166,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/66502.jpg",
                            FranchiseId = 1,
                            Name = "Shiore ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 167,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/104661.jpg",
                            FranchiseId = 1,
                            Name = "Suzume ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 168,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/86788.jpg",
                            FranchiseId = 1,
                            Name = "Shimon Hijiri",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 169,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/66501.jpg",
                            FranchiseId = 1,
                            Name = "Shibire ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 170,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/86794.jpg",
                            FranchiseId = 1,
                            Name = "Sagi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 171,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/66154.jpg",
                            FranchiseId = 1,
                            Name = "Guruko ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 172,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/66507.jpg",
                            FranchiseId = 1,
                            Name = "Iwashi Tatami",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 173,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/66500.jpg",
                            FranchiseId = 1,
                            Name = "Tobio ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 174,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/70340.jpg",
                            FranchiseId = 1,
                            Name = "Kotohime Fuuma",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 175,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/86789.jpg",
                            FranchiseId = 1,
                            Name = "Idate Morino",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 176,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/92486.jpg",
                            FranchiseId = 1,
                            Name = "Bisuke ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 177,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/103617.jpg",
                            FranchiseId = 1,
                            Name = "Manda ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 178,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/112579.jpg",
                            FranchiseId = 1,
                            Name = "Ukon ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 179,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/4/120598.jpg",
                            FranchiseId = 1,
                            Name = "Kunihisa ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 180,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/120599.jpg",
                            FranchiseId = 1,
                            Name = "Kunijirou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 181,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/120890.jpg",
                            FranchiseId = 1,
                            Name = "Matsuri ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 182,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/140139.jpg",
                            FranchiseId = 1,
                            Name = "Ran ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 183,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/168503.jpg",
                            FranchiseId = 1,
                            Name = "Gatou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 184,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/175237.jpg",
                            FranchiseId = 1,
                            Name = "Mebuki Haruno",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 185,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/193691.jpg",
                            FranchiseId = 1,
                            Name = "Natsuhi ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 186,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/202941.jpg",
                            FranchiseId = 1,
                            Name = "Sumaru ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 187,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/205357.jpg",
                            FranchiseId = 1,
                            Name = "Gantetsu ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 188,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/214103.jpg",
                            FranchiseId = 1,
                            Name = "Haku's Mother ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 189,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/4/218401.jpg",
                            FranchiseId = 1,
                            Name = "Tonton ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 190,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/218873.jpg",
                            FranchiseId = 1,
                            Name = "Kujaku ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 191,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/283833.jpg",
                            FranchiseId = 1,
                            Name = "Unkai Kurama",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 192,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/325684.jpg",
                            FranchiseId = 1,
                            Name = "Iwana Akame",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 193,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/325683.jpg",
                            FranchiseId = 1,
                            Name = "Bekkou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 194,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/14/325681.jpg",
                            FranchiseId = 1,
                            Name = "Ibara ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 195,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/325682.jpg",
                            FranchiseId = 1,
                            Name = "Tsubaki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 196,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/355456.jpg",
                            FranchiseId = 1,
                            Name = "Fukuyokana ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 197,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/355457.jpg",
                            FranchiseId = 1,
                            Name = "Shinayakana ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 198,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/464787.jpg",
                            FranchiseId = 1,
                            Name = "Sanshou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 199,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/444635.jpg",
                            FranchiseId = 1,
                            Name = "Kurobachi Kamizuru",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 200,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/13/444636.jpg",
                            FranchiseId = 1,
                            Name = "Suzumebachi Kamizuru",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 201,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/464788.jpg",
                            FranchiseId = 1,
                            Name = "Momiji ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 202,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/9/464790.jpg",
                            FranchiseId = 1,
                            Name = "Kagero ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 203,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/16/464791.jpg",
                            FranchiseId = 1,
                            Name = "Raijin ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 204,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/15/464793.jpg",
                            FranchiseId = 1,
                            Name = "Fuujin ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 205,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/10/464794.jpg",
                            FranchiseId = 1,
                            Name = "Koumei ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 206,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/464795.jpg",
                            FranchiseId = 1,
                            Name = "Ruiga ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 207,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/8/508743.jpg",
                            FranchiseId = 1,
                            Name = "Futa Kagetsu",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 208,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/12/508744.jpg",
                            FranchiseId = 1,
                            Name = "Toubei Kagetsu",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 209,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/5/508745.jpg",
                            FranchiseId = 1,
                            Name = "Tsukiko Kagetsu",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 210,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/7/508742.jpg",
                            FranchiseId = 1,
                            Name = "Mai Kagetsu",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 211,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/6/508741.jpg",
                            FranchiseId = 1,
                            Name = "Kikunojou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 212,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/11/508740.jpg",
                            FranchiseId = 1,
                            Name = "Shura Sanjurou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 213,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/508923.jpg",
                            FranchiseId = 1,
                            Name = "Yurinojou ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 214,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/3/508924.jpg",
                            FranchiseId = 1,
                            Name = "Hanzaki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 215,
                            CharacterImage = "https://cdn.myanimelist.net/images/characters/2/508925.jpg",
                            FranchiseId = 1,
                            Name = "Houki ",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 216,
                            CharacterImage = "https://beta.vndb.org/ch/30/27930.jpg",
                            FranchiseId = 2,
                            Name = "Ichinose Kotomi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 217,
                            CharacterImage = "https://beta.vndb.org/ch/83/55083.jpg",
                            FranchiseId = 2,
                            Name = "Okazaki Tomoya",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 218,
                            CharacterImage = "https://beta.vndb.org/ch/28/27928.jpg",
                            FranchiseId = 2,
                            Name = "Furukawa Nagisa",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 219,
                            CharacterImage = "https://beta.vndb.org/ch/31/27931.jpg",
                            FranchiseId = 2,
                            Name = "Sakagami Tomoyo",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 220,
                            CharacterImage = "https://beta.vndb.org/ch/29/27929.jpg",
                            FranchiseId = 2,
                            Name = "Ibuki Fuuko",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 221,
                            CharacterImage = "https://beta.vndb.org/ch/27/27927.jpg",
                            FranchiseId = 2,
                            Name = "Fujibayashi Kyou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 222,
                            CharacterImage = "https://beta.vndb.org/ch/34/27934.jpg",
                            FranchiseId = 2,
                            Name = "Sunohara Youhei",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 223,
                            CharacterImage = "https://beta.vndb.org/ch/33/27933.jpg",
                            FranchiseId = 2,
                            Name = "Fujibayashi Ryou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 224,
                            CharacterImage = "https://beta.vndb.org/ch/76/55076.jpg",
                            FranchiseId = 2,
                            Name = "Sakagami Takafumi",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 225,
                            CharacterImage = "https://beta.vndb.org/ch/32/27932.jpg",
                            FranchiseId = 2,
                            Name = "Miyazawa Yukine",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 226,
                            CharacterImage = "https://beta.vndb.org/ch/34/97234.jpg",
                            FranchiseId = 3,
                            Name = "Makise Kurisu",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 227,
                            CharacterImage = "https://beta.vndb.org/ch/95/97195.jpg",
                            FranchiseId = 3,
                            Name = "Shiina Mayuri",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 228,
                            CharacterImage = "https://beta.vndb.org/ch/36/97236.jpg",
                            FranchiseId = 3,
                            Name = "Amane Suzuha",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 229,
                            CharacterImage = "https://beta.vndb.org/ch/38/97238.jpg",
                            FranchiseId = 3,
                            Name = "Hashida Itaru",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 230,
                            CharacterImage = "https://beta.vndb.org/ch/35/97235.jpg",
                            FranchiseId = 3,
                            Name = "Akiha Rumiho",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 231,
                            CharacterImage = "https://beta.vndb.org/ch/46/28046.jpg",
                            FranchiseId = 3,
                            Name = "Tennouji Yuugo",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 232,
                            CharacterImage = "https://beta.vndb.org/ch/38/28038.jpg",
                            FranchiseId = 3,
                            Name = "Kiryuu Moeka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 233,
                            CharacterImage = "https://beta.vndb.org/ch/44/28044.jpg",
                            FranchiseId = 3,
                            Name = "Urushibara Ruka",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 234,
                            CharacterImage = "https://beta.vndb.org/ch/29/10729.jpg",
                            FranchiseId = 3,
                            Name = "Okabe Rintarou",
                            VoteCount = 0
                        },
                        new
                        {
                            Id = 235,
                            CharacterImage = "https://beta.vndb.org/ch/29/97229.jpg",
                            FranchiseId = 3,
                            Name = "Tennouji Nae",
                            VoteCount = 0
                        });
                });

            modelBuilder.Entity("CharacterSorterSite.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateofCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creator = "Masashi Kishimoto",
                            DateofCreation = new DateTime(1999, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Naruto"
                        },
                        new
                        {
                            Id = 2,
                            Creator = "Key",
                            DateofCreation = new DateTime(2004, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clannad"
                        },
                        new
                        {
                            Id = 3,
                            Creator = "5pb",
                            DateofCreation = new DateTime(2009, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Steins; Gate"
                        },
                        new
                        {
                            Id = 4,
                            Creator = "07th Expansion",
                            DateofCreation = new DateTime(2007, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Umineko"
                        },
                        new
                        {
                            Id = 5,
                            Creator = "Gainax",
                            DateofCreation = new DateTime(2007, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gurren Lagann"
                        },
                        new
                        {
                            Id = 6,
                            Creator = "Studio Gokumi",
                            DateofCreation = new DateTime(2014, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yuuki Yuuna's a Hero"
                        });
                });

            modelBuilder.Entity("CharacterSorterSite.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterThatLostId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterThatWonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CharacterSorterSite.Models.Character", b =>
                {
                    b.HasOne("CharacterSorterSite.Models.Franchise", "Franchise")
                        .WithMany("Characters")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CharacterSorterSite.Models.Match", b =>
                {
                    b.HasOne("CharacterSorterSite.Models.Character", null)
                        .WithMany("Matches")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("CharacterSorterSite.Models.Character", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("CharacterSorterSite.Models.Franchise", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
